version: '3'
services:
    servicio: # dar el nombre de SERVICE de .env 
      image: nginx:alpine
      container_name: nginx_server
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - proxy
      volumes:
        - ./froet:/usr/share/nginx/html
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE}.entrypoints=http"
        - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-https-redirect"
        - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
        - "traefik.http.routers.${SERVICE}-secure.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${SERVICE}-secure.tls=true"
        - "traefik.http.routers.${SERVICE}-secure.tls.certresolver=http"
        - "traefik.http.routers.${SERVICE}-secure.service=${SERVICE}"
        - "traefik.http.services.${SERVICE}.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true